stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw


  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim/train_processed.csv 
    - data/interim/test_processed.csv
    - src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    - feature_engineering.ngram_range
    outs:
    - data/processed

  model_building:
    cmd: python src/model/model_building.py
    deps:
    - data/processed/X_train_tfidf.pkl
    - data/processed/y_train.pkl
    - src/model/model_building.py
    params:
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - models/lgbm_model.pkl
    # - models/tfidf_vectorizer.pkl
